MaxProjectWebApp_Homepage:
    path:     /
    defaults: { _controller: MaxProjectWebAppBundle:Default:index }

MaxProjectWebApp_Views:
    path: /views/{resources}
    defaults: { _controller: MaxProjectWebAppBundle:Default:resources}
