MaxProject\ProjectManagmentBundle\Entity\Project:
    type: entity
    table: Project
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        description:
            type: text
        dateStart:
            type: date
        dateEnd:
            type: date
        avaibleLabel:
            type: array
        axes:
            type: array

    oneToMany:
        members:
            targetEntity: User
            mappedBy: id
        backlog:
            targetEntity: Task
            mappedBy: project
        sprints:
            targetEntity: Sprint
            mappedBy: id