MaxProject\ProjectManagmentBundle\Entity\Task:
    type: entity
    table: Task
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        shortName:
            type: string
            unique: true
        name:
            type: string
        description:
            type: text
        axe:
            type: string
        difficulty:
            type: integer
        labels:
            type: array
        dueDate:
            type: date
        state:
            type: string
    oneToMany:
        attachments:
            targetEntity: Attachment
            mappedBy: id
        associateMembers:
            targetEntity: User
            mappedBy: id
        subTask:
            targetEntity: Task
            mappedBy: id
    manyToOne:
        project:
            targetEntity: Project
            inversedBy: backlog
        parentTask:
            targetEntity: Task
            inversedBy: subTask